version: "2"
services:
    mysql:
        container_name: mysql
        image: mysql:8.0.19
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: 1q2w3e4r!
            MYSQL_DATABASE: testdb
        ports:
            - "3306:3306"
        networks:
            backend-network:
                ipv4_address: 192.132.0.1
        volumes:
            - ./mysql:/var/lib/mysql
        restart: always
    web1:
        container_name: web1
        image: php:lrv-7.1
        ports: 
            - "80:80"
        volumes:
            - ./web1:/var/www/html
        environment:
            - TZ=Asia/Bangkok
        restart: always
        networks:
            backend-network:
                ipv4_address: 192.132.0.2
 
    phpmyadmin:
        container_name: phpmyadmin
        image: jayudev/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - 8888:80
        networks:
            backend-network:
                ipv4_address: 192.132.0.4
        restart: always        
volumes:
    volume:

networks:
    backend-network:
        driver: bridge
        ipam:
            config:
                - subnet: 192.132.100.0/16
                  gateway: 192.132.100.254
